Tumor size over time
imsweb/algorithms pull request #178
Opened 2024-01-24 20:27 UTC by bekeles

closes #177

2024-01-24 21:49 UTC, depryf requested changes

2024-01-24 21:49 UTC, depryf commented on src/main/java/com/imsweb/algorithms/Algorithms.java
> +    public static final String FIELD_TUMOR_SIZE = "csTumorSize";
Aren't these two standard fields? I know it's a bit silly, but there is a group of standard fields and another one after that with the non-standard. Could you please move these to the standard block?

2024-01-24 21:49 UTC, depryf commented on src/main/java/com/imsweb/algorithms/tumorsizeovertime/TumorSizeOverTimeUtils.java
> +    public static final String ALG_NAME = "Tumor Size Over Time";
By convention, we put the owner in front of the name. Can you please put "SEER" in front of the current name?

2024-01-24 21:53 UTC, bekeles commented on src/main/java/com/imsweb/algorithms/Algorithms.java
> +    public static final String FIELD_TUMOR_SIZE = "csTumorSize";
Sure. I didn't notice that.

2024-01-24 21:54 UTC, bekeles commented on src/main/java/com/imsweb/algorithms/tumorsizeovertime/TumorSizeOverTimeUtils.java
> +    public static final String ALG_NAME = "Tumor Size Over Time";
Sure!

2024-01-26 14:44 UTC, bekeles commented
@depryf did this slip away from your list?

2024-01-26 14:46 UTC, depryf commented
It sure did! Looks good, merging now.

2024-01-26 14:46 UTC, depryf approved these changes

2024-01-26 14:46 UTC, merged