Replace openCSV dependency by FastCSV (#187)
imsweb/algorithms pull request #197
Opened 2024-11-22 17:03 UTC by CookiIMS

2024-11-22 17:42 UTC, depryf requested changes
I didn't review everything; no need since I assume almost all changes are going to have the same problem.

2024-11-22 17:42 UTC, depryf commented on src/main/java/com/imsweb/algorithms/ayasiterecode/AyaSiteRecodeUtils.java
> +            File csvFile = new File("src/main/resources/ayasiterecode/" + filename);
This change is not going to work.

All those CSV files are internal resources to the library.  When the library runs as part of another project, those "files" will be available on the class path only; there won't be a physical file for it anywhere on the file system (I mean, there will be, but it will be the JAR file of the library; that's the physical location where they will be.

Unfortunately, while developing in IntellIj, there is an actual physical file for it (in the source code), and so this works when you run your test in IntelliJ. But it won't work when the library is packaged into a JAR file.

You have to use the input stream "is",  just like the previous code was doing.  And just like before, you have to first create a Reader (because I don't think fastCSV accepts an InputStream, but I am pretty sure it accepts a Reader). 

I think it should look like this:

```java
try (Reader reader = new InputStreamReader(is, StandardCharsets.UTF_8);
       CsvReader<CsvRecord> reader = CsvReader.builder().fieldSeparator(txt ? ';' : ',').ofCsvRecord(reader)) {
            ...
```

Please review all your changes. If the previous code used a file, you should keep using a file (it might be the case for some unit tests, although that's unlikely). Any place that used an input stream needs to keep using that same input stream.

2024-11-25 16:51 UTC, CookiIMS commented on src/main/java/com/imsweb/algorithms/ayasiterecode/AyaSiteRecodeUtils.java
> +            File csvFile = new File("src/main/resources/ayasiterecode/" + filename);
I think I got them all fixed; please let me know if I missed anything!

2024-11-26 15:30 UTC, depryf commented
The changes look good. Thanks.  I saw you replaced a few readers from ASCII to UTF-8.   I don't think it's a big deal (if the data was pure ASCII, then it was also UTF-8).  I don't think this is going to be create any problems, so I am letting that go. The rest looks good.  The build failed because of the code duplication, but I am not sure I care too much about that. 

I am going to merge the changes. Thanks again!

2024-11-26 15:30 UTC, merged